### Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [ ]:
## create a 1D array
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a.shape) # shape of the array
print(a.ndim) # number of dimensions
print(a.dtype) # data type
print(a.size) # total number of elements
print(a.itemsize) # size of each element in bytes

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1
int64
5
8


In [4]:
arr2 = np.array([2,4,5,6,7])
print(arr2)
print(arr2.shape)

[2 4 5 6 7]
(5,)


In [5]:
## reshape it
arr2 = arr2.reshape(5,1)
print(arr2)
print(arr2.shape)

[[2]
 [4]
 [5]
 [6]
 [7]]
(5, 1)


In [7]:
## create a 2D array    
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(type(arr2))
print(arr2.shape)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2


In [8]:
## Inbuilt functions to create arrays
arr3 = np.arange(0,10,2).reshape(5,1)
print(arr3)

[[0]
 [2]
 [4]
 [6]
 [8]]


In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
## Vectorized operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b) # addition
print(a - b) # subtraction
print(a * b) # multiplication
print(a / b) # division
print(a ** 2) # power

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [14]:
# Universal functions
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.add(a, b)) # addition
print(np.subtract(a, b)) # subtraction
print(np.multiply(a, b)) # multiplication
print(np.divide(a, b)) # division
print(np.power(a, 2)) # power
print(np.sqrt(a)) # square root
print(np.exp(a)) # exponential
print(np.log(a)) # logarithm
print(np.sin(b)) # sine
print(np.cos(a)) # cosine

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[-0.7568025  -0.95892427 -0.2794155 ]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [16]:
# array slicing and indexing
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a[0]) # access first row
print(a[0, 1]) # access element at row 0, column 1
print(a[1, :]) # access row 1
print(a[:, 1]) # access column 1
print(a[1:3, 0:2]) # access sub-array
print(a[1:3, :]) # access sub-array
print(a[:, 1:3]) # access sub-array
print(a[0:2, 1:3]) # access sub-array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
2
[4 5 6]
[2 5 8]
[[4 5]
 [7 8]]
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[2 3]
 [5 6]]


In [18]:
# Statistical concepts - Normalization
# to have mean = 0 and std = 1
a = np.array([1, 2, 3])
print(a)
print("Mean: ", a.mean())
print("Std: ", a.std())
a = (a - a.mean()) / a.std()
print(a) # normalized array 
print(a.var()) # variance


[1 2 3]
Mean:  2.0
Std:  0.816496580927726
[-1.22474487  0.          1.22474487]
0.9999999999999999


In [ ]:
# Logical operations
a = np.array([1, 2, 3,4,5,6,7,8,9,10])
print(a)
print(a > 5) # greater than
print(a[a > 5]) # greater than
print(a[a < 5]) # less than
print(a[a == 5]) # equal to
print(a[a != 5]) # not equal to
print(a[a >= 5]) # greater than or equal to


[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[1 2 3 4]
[5]
[ 1  2  3  4  6  7  8  9 10]
[ 5  6  7  8  9 10]


In [21]:
print(a[(a >= 5) | (a <= 8)]) # greater than or equal to 5 or less than or equal to 8
print(a[(a >= 5) & (a <= 8)]) # greater than or equal to 5 and less than or equal to 8

[ 1  2  3  4  5  6  7  8  9 10]
[5 6 7 8]
